### ISSUE TITLE
Minor issues

### ISSUE THREAD

**Issue by stephanmg** [VRL-Studio/VRL-Studio#10]
Dear Michael,

two issues (on the current master and stable 0.4 branch):

i. Clicking on Help->Version Management results in an IO Exception on Ubuntu 14.04 (Trusty Tahr).
(This is the case because the file does not exist - maybe the file was not copied correctly during deployment? File: /home/stephan/Code/git/VRL-Studio/VRL-Studio/dist-final/linux/VRL-Studio/.application/resources/studio-resources/help/version-management.html)

Exception:
```Java
Mar 04, 2015 3:11:56 PM eu.mihosoft.vrl.system.VSysUtil openURI
SEVERE: null
java.io.IOException: Failed to show URI:file:/home/stephan/Code/git/VRL-Studio/VRL-Studio/dist-final/linux/VRL-Studio/.application/resources/studio-resources/help/version-management.html
	at sun.awt.X11.XDesktopPeer.launch(XDesktopPeer.java:114)
	at sun.awt.X11.XDesktopPeer.browse(XDesktopPeer.java:98)
	at java.awt.Desktop.browse(Desktop.java:386)
	at eu.mihosoft.vrl.system.VSysUtil.openURI(VSysUtil.java:619)
	at eu.mihosoft.vrlstudio.main.Studio.versionManagementActionPerformed(Studio.java:2008)
	at eu.mihosoft.vrlstudio.main.Studio.access$4200(Studio.java:105)
	at eu.mihosoft.vrlstudio.main.Studio$48.actionPerformed(Studio.java:1110)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	at java.awt.Component.processMouseEvent(Component.java:6516)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3312)
	at java.awt.Component.processEvent(Component.java:6281)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4872)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
	at java.awt.Container.dispatchEventImpl(Container.java:2273)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:740)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:699)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:713)
	at java.awt.EventQueue$4.run(EventQueue.java:711)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:710)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

ii. Start button's changes label to "stop" after once the Start button has been pressed, see screenshot, note this happens also on Ubuntu 14.04.:
![Sample](https://cloud.githubusercontent.com/assets/1750463/6485380/b3332f18-c283-11e4-8794-c3707b25215c.png)

Don't know if this is relevant at all but here it is:
java version "1.7.0_75"
OpenJDK Runtime Environment (IcedTea 2.5.4) (7u75-2.5.4-1~trusty1)
OpenJDK 64-Bit Server VM (build 24.75-b04, mixed mode)

iii. Sporadic crashes (don't know if this is directly related to VRL-Studio but Java3D?):
See error log here:
https://www.stephangrein.de/files/vrl/hs_err_pid19260.log 

If necessary I'll provide more detail.

Best,
Stephan

**Comment by stephanmg** [comment]
Ad i.: Install VRL-Documentation if necessary only if we have the corresponding VRL-Documentation repository, i. e. see VRL-Studio README how to configure the path.

Ad ii.: This is really a bug, should be fixed.

Ad iii.: Seems to happen also with the closed-source ATI driver on my desktop PC (but not as frequent as with the free ATI driver). Don't know if this is related directly to VRL-Studio.

**Comment by miho** [comment]
Regarding iii: your crash report gives me the impression that this is somehow X11 related. At least the crash happens in  `C  [libX11.so.6+0x328bd]`. Which is also indicated by this statement `The crash happened outside the Java Virtual Machine in native code.`

**Comment by stephanmg** [comment]
Okay, i now can reproduce the crash!
Will upload soon a screen capture vid.

Best

**Comment by stephanmg** [comment]
Is this solved?

**Comment by miho** [comment]
i)   is not a bug. 
ii)  is fixed
iii) see my comment above (March 6, 2015)

**Comment by stephanmg** [comment]
Should we close this then?
