### ISSUE TITLE
NPE in JEditorPane.registerEditorKitForContentType

### ISSUE THREAD

**Issue by miho** [VRL-Studio/VRL-Studio#11]
error while loading resources in JEditorPane can only
be prevented by manually defining a context classloader

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
at java.util.Hashtable.put(Hashtable.java:459)
at javax.swing.JEditorPane.registerEditorKitForContentType(JEditorPane.java:1247)
at javax.swing.JEditorPane.registerEditorKitForContentType(JEditorPane.java:1229)
at javax.swing.JEditorPane.loadDefaultKitsIfNecessary(JEditorPane.java:1307)
at javax.swing.JEditorPane.getKitTypeRegistry(JEditorPane.java:1264)
at javax.swing.JEditorPane.getEditorKitClassNameForContentType(JEditorPane.java:1260)
at javax.swing.JTextPane.<init>(JTextPane.java:94)
at eu.mihosoft.vrl.visual.MessageBox.<init>(MessageBox.java:143)
```

see http://lists.apple.com/archives/java-dev/2009/Dec/msg00074.html

**Comment by miho** [comment]
related bugs:

https://youtrack.jetbrains.com/issue/IDEA-121469
https://bugs.launchpad.net/ubuntu/+source/sweethome3d/+bug/1442958
