### ISSUE TITLE
How to run a VRL program from terminal/command line?

### ISSUE THREAD

**Issue by drapostolos** [VRL-Studio/VRL-Studio#36]
I have made a VRL project (it has a start component, with some components (from my plugin) connected and lastly a stop component). The programs runs successfully from VRL-Studio.

How can I export this program to an executable and run it from command line?

I have tried the `File->Development->Export Project As Console App` and saved it to a zip file (then unzipped it).
Running the the `run.sh` file in above folder gives me this exception:

```
>> detected x86 (64 bit) os
>> integrated jre not found!
 --> executing installed java version
--------------------------------------------------------------------------------
=> VRL-0.4.4.0.3, build: 2018/10/31 13:49:41
=> Groovy-2.4.12
--------------------------------------------------------------------------------
>> VRL Version: 0.4.4.0.3, build: 2018/10/31 13:49:41
 --> running on Java Version: 1.8.0_241 (Oracle Corporation)
 --> OS: Mac OS X (x64)
 --> pid: 64504
>> Property Folder Options:
 --> using custom property folder, path: property-folder/
 --> initializing property folder: property-folder
>> installing payload plugins: [done]
>> adding "file:/Users/alexanderpoulikakos/test-losing-live/.application/lib/VRL.jar" to system classpath
>> ClassPathUpdater.addAllJarsInDir("custom-lib"): directory does not exist!
>> Plugin Options:
 --> disabling checksum test
 --> no plugin path specified, using default.
>> loading plugin from cache
 --> plugin "CCS-VISUAL-SCRIPTING" found
>> Init Plugins ( #2 )
>> Plugin (1): VRL-0.4.4.0.3
>> Plugin (2): CCS-VISUAL-SCRIPTING-0.4.0
--------------------------------------------------------------------------------
>> invoking Main.run()

Oct 19, 2020 10:44:52 PM eu.mihosoft.vrl.system.VSessionRunner runMain
SEVERE: null
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at eu.mihosoft.vrl.system.VSessionRunner.runMain(VSessionRunner.java:255)
	at eu.mihosoft.vrl.system.VSessionRunner.run(VSessionRunner.java:185)
	at eu.mihosoft.vrl.system.VSessionRunner$run.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at eu.mihosoft.vrl.user.VSessionMainClass.main(VSessionMainClass.groovy:10)
Caused by: java.lang.NoClassDefFoundError: vs/GameInstaller
	at eu.mihosoft.vrl.user.Main.run(Main.groovy:13)
	... 11 more
Caused by: java.lang.ClassNotFoundException: class name: vs.GameInstaller
	at eu.mihosoft.vrl.system.VClassLoader.findClass(VClassLoader.java:169)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at eu.mihosoft.vrl.system.VSessionRunner$1.loadClass(VSessionRunner.java:159)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 12 more

--------------------------------------------------------------------------------
```

The `vs.GameInstaller` class is part of my plugin: `CCS-VISUAL-SCRIPTING-0.4.0`.

**Comment by drapostolos** [comment]
@miho Is there anything I'm doing wrong or missing? thanks!

**Comment by stephanmg** [comment]
@drapostolos I remember I had a similiar issue.

I am not sure: But did you export your package?

**Comment by drapostolos** [comment]
@stephanmg How do I export my plugin (I assume that is what you mean with package, right?)

**Comment by stephanmg** [comment]
@drapostolos yeah, this is a shot in the dark still. Yes I mean package, I think `exportPackage`.

**Comment by drapostolos** [comment]
@stephanmg is this how you mean?
https://github.com/drapostolos/vrl-plugin/blob/master/src/main/java/vrl/service/PluginConf.java#L25

**Comment by stephanmg** [comment]
@drapostolos yes, but do this ` exportPackage("com.your.package");` in the plugin configurator's constructor.

**Comment by drapostolos** [comment]
@stephanmg I Will try that! thx

**Comment by drapostolos** [comment]
@stephanmg it worked! THX! 😀

**Comment by stephanmg** [comment]
> @stephanmg it worked! THX! 😀

Glad to hear. Enjoy.
