### ISSUE TITLE
Is it possible to loop over components?

### ISSUE THREAD

**Issue by alexander-poulikakos** [VRL-Studio/VRL-Studio#41]
Let's say I have the following component, with 3 methods.
![image](https://user-images.githubusercontent.com/16044466/109874038-e1b64e00-7c6e-11eb-973a-3704f3bdba44.png)
where method `m2(int)` takes an integer argument. 

Now I want to run this component 3 times, with the values 1, 5, 10 given as argument to `m2(int)`. It can look like this:
![image](https://user-images.githubusercontent.com/16044466/109875027-2ee6ef80-7c70-11eb-80f0-50381b915abe.png)

However, I would like to avoid duplicating the component and put it in a loop instead where the `m2(int)` is fed with the three different values. Is that possible? Are there any tricks to achieve this? Can there be a general way of doing it, that can be applied to any components, or a chain of multiple components?

In my real world situation the number of iterations would be more than 3 and number of methods on the component can be arbitrary.

**Comment by miho** [comment]
You can build a loop component yourself. It's quite simple:

1. ) Create control flow:

![image](https://user-images.githubusercontent.com/225266/123905626-fd0e3d00-d972-11eb-9656-bb68f5b459d3.png)

2) Create a component that performs the looping:

![image](https://user-images.githubusercontent.com/225266/123905722-216a1980-d973-11eb-9922-6b880f7076cd.png)

3) Perform the looping:

![image](https://user-images.githubusercontent.com/225266/123905844-61c99780-d973-11eb-97a7-b491b8e8684f.png)


Background information:

There are two prototypes hidden in the code that add looping as first-class concept to the control flow. One merely adds two marker components (like start and stop) to the control flow. The other adds a container. Components can be added by dragging over the container (similar to what we do in [VWorkflows](https://github.com/miho/VWorkflows)). 

In the VWorkflows based VRL version we use the container approach from VWorkflows. This has the advantage that we support common loops visually. 

In the end the Groovy based approach won in the current VRL implementation simply because it is the most flexible.

**Comment by alexander-poulikakos** [comment]
Thanks for response @miho !

I'm a bit confused about how the _Input_/_Output_ and _Main_ components in above Example works. Is it documented somewhere? Feels like there is some magic going on 😛 

From my understanding the above example will only loop one method call on a component (or the entire program as in your example). In the above use case (see first post) I'd like to have a set of methods called on the component inside the loop, not just one method. Sure it can probably be solved by providing an extra method on the Loop component that takes a list of strings with method names to call on the component, and use reflection internally. But that sounds too messy and non-flexible.

Would be awesome if there was a first class looping component that could be used inside a control/Work flow visually in VRL-Studio.

PS. I have never seen about [VWorkflows](https://github.com/miho/VWorkflows) before. Is that something that could be used as an IDE, instead of VRL-Stiudio?

**Comment by alexander-poulikakos** [comment]
Hi @miho 

Would it be possible to run your example program above (Loop/LoopMe/Main) from a Console App? I tried running it as is first, but that gave me the error that `Main.run()` method only accepts either no args, or a `String[]`. I modified it so it uses a `String[]`.

It works fine when running from within VRL-Studio (by clicking the `invoke` button on the `ForLoop` component. But when exporting it to a Console App, then unzipping it and running the `run.sh` I get bellow error, as if the `Main` and `ForLoop` components are ignored. Any ideas how to get around this?

```
>> invoking Main.run(String[])

Sep 16, 2021 1:22:03 AM eu.mihosoft.vrl.system.VSessionRunner runMain
SEVERE: null
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at eu.mihosoft.vrl.system.VSessionRunner.runMain(VSessionRunner.java:233)
	at eu.mihosoft.vrl.system.VSessionRunner.run(VSessionRunner.java:185)
	at eu.mihosoft.vrl.system.VSessionRunner$run.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at eu.mihosoft.vrl.user.VSessionMainClass.main(VSessionMainClass.groovy:10)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at org.codehaus.groovy.runtime.BytecodeInterface8.objectArrayGet(BytecodeInterface8.java:363)
	at eu.mihosoft.vrl.user.ArrayToInt.m(ArrayToInt.groovy:10)
	at eu.mihosoft.vrl.user.ArrayToInt$m.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at eu.mihosoft.vrl.user.Main.run(Main.groovy:25)
	... 11 more
```

![image](https://user-images.githubusercontent.com/16044466/133558755-b45b2061-659d-4c2c-a314-20f6e6e35512.png)


![image](https://user-images.githubusercontent.com/16044466/133558334-4edeb7c5-ff5b-40b9-bf95-5e889eddca43.png)

![image](https://user-images.githubusercontent.com/16044466/133558392-1d6638e9-121f-4673-8979-b7dabbb71579.png)

![image](https://user-images.githubusercontent.com/16044466/133558701-c359211b-234b-45b1-a207-9dd3e6a74c89.png)
